services:
  scraper:
    image: ghcr.io/aerya/correzeboostemploi:latest
    container_name: correzeboostemploi
    restart: always
    environment:
      DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/XXXXXXXX/YYYYYYYY"
      BANNED_KEYWORDS: "comptable,ménage,cuisine,cuisinier,cuisinière,plongeur,aide-soignant"
      SCHEDULE_START: "7"
      SCHEDULE_END: "19"
      SCHEDULE_INTERVAL_HOURS: "2"
      MAX_PAGES: "10"
      DATA_DIR: /data
    volumes:
      - /home/aerya/docker/correzeboostemploi:/data
